
moonvar a = 10
moonvar b = 10
moonvar c = if (b >= a) { fn(x){x * 2} } else { fn(x){x * 3} }

moonvar myList = [1,2,3,4,5]

moonvar fib = fn(x){ 
    if (x <= 1) {
        return x
    }

    return fib(x-1) + fib(x-2)
}

moonvar myFib = fib(10)

moonvar funcOne = fn(x){x*10}

moonvar TEST = fn(x){x * 2}

moonvar TestTWO = fn(x){x + 2}

moonvar mu = OwO 10 ~> TestTWO;
moonvar elixirLike = OwO "Eae Beleza" ~> String_Upcase ~> String_Split;
moonvar overflow = OwO mu ~> TestTWO ~> TestTWO ~> TestTWO ~> TestTWO;



